baseURL = "https://intermezzio.github.io/bb-site/"
languageCode = "en-us"
title = "BB-Gr8"
themesDir = "themes/"
theme = "hugo-hero-theme"
publishDir = "docs/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "BB-Gr8 is a wireless, remote-controlled spherical robot modeled after the legendary robot found in Star Wars."
    meta_og_title = "BB-Gr8"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "BB-Gr8 is a wireless, remote-controlled spherical robot modeled after the legendary robot found in Star Wars."

[[menu.main]]
	name = "Features"
	url = "/features/"
    weight = 1

[[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


# [[menu.main]]
#     name = "History"
#     url = "/history/"
#     weight = 3

# [[menu.main]]
#     name = "Contact"
#     url = "/contact/"
#     weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
